import BeerColumnTitle from "./BeerColumnTitle";
import BeerElement from "./BeerElement";

export default function BeerTable() {
  const beerElements = [
    {
      title: 'WHEAT BEER',
      titletextColor: 'text-wheatBeerBorder',
      elements: [
        {
          number: '1',
          initialDensity: '1.026-1.036',
          finalDensity: '1.006-1.009',
          name: 'Berliner Weisse',
          ABV: '2.5-3.6%',
          IBU: '3-12',
          SRM: '2-4',
          bgColor: 'bg-wheatBeer',
          borderColor: 'border-wheatBeerBorder',
        },
        {
          number: '4',
          initialDensity: '1.042-1.055',
          finalDensity: '1.008-1.012',
          name: 'Belgian White',
          ABV: '4.5-5.5%',
          IBU: '15-28',
          SRM: '2-4',
          bgColor: 'bg-wheatBeer',
          borderColor: 'border-wheatBeerBorder',
        },
        {
          number: '7',
          initialDensity: '1.042-1.055',
          finalDensity: '1.008-1.018',
          name: 'American Wheat',
          ABV: '3.5-5.0%',
          IBU: '5-20',
          SRM: '2-8',
          bgColor: 'bg-wheatBeer',
          borderColor: 'border-wheatBeerBorder',
        },
        {
          number: '14',
          initialDensity: '1.040-1.056',
          finalDensity: '1.008-1.016',
          name: 'Weizen- bier',
          ABV: '4.3-5.6%',
          IBU: '8-15',
          SRM: '3-9',
          bgColor: 'bg-wheatBeer',
          borderColor: 'border-wheatBeerBorder',
        },
        {
          number: '27',
          initialDensity: '1.048-1.056',
          finalDensity: '1.008-1.016',
          name: 'Dunkel- weizen',
          ABV: '4.5-6.0%',
          IBU: '10-15',
          SRM: '17-23',
          bgColor: 'bg-wheatBeer',
          borderColor: 'border-wheatBeerBorder',
        },
        {
          number: '41',
          initialDensity: '1.066-1.080',
          finalDensity: '1.016-1.028',
          name: 'Weizen- bock',
          ABV: '6.5-9.6%',
          IBU: '12-25',
          SRM: '10-30',
          bgColor: 'bg-wheatBeer',
          borderColor: 'border-wheatBeerBorder',
        }

      ]   
    },
    {
      title: 'LAMBIC & SOUR',
      titletextColor: 'text-lambicSourBorder',
      elements: [
        {
          number: '2',
          initialDensity: '1.044-1.056',
          finalDensity: '1.006-1.012',
          name: 'Lambic',
          ABV: '4.7-6.4%',
          IBU: '5-15',
          SRM: '4-15',
          bgColor: 'bg-lambicSour',
          borderColor: 'border-lambicSourBorder',
        },
        {
          number: '5',
          initialDensity: '1.044-1.056',
          finalDensity: '1.006-1.012',
          name: 'Gueuze',
          ABV: '4.7-6.4%',
          IBU: '5-15',
          SRM: '4-15',
          bgColor: 'bg-lambicSour',
          borderColor: 'border-lambicSourBorder',
        },
        {
          number: '8',
          initialDensity: '1.044-1.056',
          finalDensity: '1.006-1.012',
          name: 'Faro',
          ABV: '4.5-5.5%',
          IBU: '5-15',
          SRM: '4-15',
          bgColor: 'bg-lambicSour',
          borderColor: 'border-lambicSourBorder',
        },
        {
          number: '15',
          initialDensity: '1.040-1.072',
          finalDensity: '1.008-1.016',
          name: 'Fruit Beer',
          ABV: '4.7-7.0%',
          IBU: '15-21',
          SRM: 'N/A',
          bgColor: 'bg-lambicSour',
          borderColor: 'border-lambicSourBorder',
        },
        {
          number: '28',
          initialDensity: '1.042-1.060',
          finalDensity: '1.008-1.016',
          name: 'Flanders Red',
          ABV: '4.0-5.8%',
          IBU: '14-25',
          SRM: '10-16',
          bgColor: 'bg-lambicSour',
          borderColor: 'border-lambicSourBorder',
        },
        {
          number: '42',
          initialDensity: '1.042-1.060',
          finalDensity: '1.008-1.016',
          name: 'Oud Bruin',
          ABV: '4.0-6.5%',
          IBU: '14-30',
          SRM: '12-20',
          bgColor: 'bg-lambicSour',
          borderColor: 'border-lambicSourBorder',
        }

      ]   
    },
    {
      title: 'BELGIAN ALE',
      titletextColor: 'text-belgianAleBorder',
      elements: [
        {
          number: '3',
          initialDensity: '1.065-1.085',
          finalDensity: '1.014-1.020',
          name: 'Belgian Gold Ale',
          ABV: '7.0-9.0%',
          IBU: '25-35',
          SRM: '4-6',
          bgColor: 'bg-belgianAle',
          borderColor: 'border-belgianAleBorder',
        },
        {
          number: '6',
          initialDensity: '1.070-1.100',
          finalDensity: '1.016-1.024',
          name: 'Tripel',
          ABV: '7.0-10.0%',
          IBU: '10-20',
          SRM: '4-7',
          bgColor: 'bg-belgianAle',
          borderColor: 'border-belgianAleBorder',
        },
        {
          number: '9',
          initialDensity: '1.052-1.080',
          finalDensity: '1.010-1.015',
          name: 'Saison',
          ABV: '4.5-8.1%',
          IBU: '25-40',
          SRM: '4-10',
          bgColor: 'bg-belgianAle',
          borderColor: 'border-belgianAleBorder',
        },
        {
          number: '16',
          initialDensity: '1.040-1.055',
          finalDensity: '1.008-1.013',
          name: 'Belgian Pale Ale',
          ABV: '3.9-5.6%',
          IBU: '20-35',
          SRM: '4-14',
          bgColor: 'bg-belgianAle',
          borderColor: 'border-belgianAleBorder',
        },
        {
          number: '29',
          initialDensity: '1.065-1.098',
          finalDensity: '1.014-1.024',
          name: 'Belgian Dark Ale',
          ABV: '7.0-12.0%',
          IBU: '25-40',
          SRM: '7-20',
          bgColor: 'bg-belgianAle',
          borderColor: 'border-belgianAleBorder',
        },
        {
          number: '43',
          initialDensity: '1.065-1.085',
          finalDensity: '1.012-1.018',
          name: 'Dubbel',
          ABV: '3.2-8.0%',
          IBU: '20-25',
          SRM: '10-20',
          bgColor: 'bg-belgianAle',
          borderColor: 'border-belgianAleBorder',
        }

      ]   
    },
    {
      title: 'PALE ALE',
      titletextColor: 'text-paleAleBorder',      
      elements: [
        {
          number: '10',
          initialDensity: '1.043-1.056',
          finalDensity: '1.008-1.016',
          name: 'Pale Ale',
          ABV: '4.5-5.5%',
          IBU: '20-40',
          SRM: '4-11',
          bgColor: 'bg-paleAle',
          borderColor: 'border-paleAleBorder',
        },
        {
          number: '17',
          initialDensity: '1.045-1.056',
          finalDensity: '1.010-1.015',
          name: 'American Pale Ale',
          ABV: '4.5-5.7%',
          IBU: '20-40',
          SRM: '4-11',
          bgColor: 'bg-paleAle',
          borderColor: 'border-paleAleBorder',
        },
        {
          number: '30',
          initialDensity: '1.050-1.075',
          finalDensity: '1.012-1.018',
          name: 'India Pale Ale',
          ABV: '5.1-7.6%',
          IBU: '40-60',
          SRM: '8-14',
          bgColor: 'bg-paleAle',
          borderColor: 'border-paleAleBorder',
        },
        {
          number: '44',
          initialDensity: '1.043-1.056',
          finalDensity: '1.008-1.016',
          name: 'American Amber Ale',
          ABV: '4.5-5.7%',
          IBU: '20-40',
          SRM: '11-18',
          bgColor: 'bg-paleAle',
          borderColor: 'border-paleAleBorder',
        },
      ]   
    },
    {
      title: 'ENGLISH BITTER',
      titletextColor: 'text-englishBitterBorder',    
      elements: [
        {
          number: '18',
          initialDensity: '1.030-1.038',
          finalDensity: '1.006-1.012',
          name: 'Ordinary Bitter',
          ABV: '3.0-3.8%',
          IBU: '20-35',
          SRM: '6-12',
          bgColor: 'bg-englishBitter',
          borderColor: 'border-englishBitterBorder',
        },
        {
          number: '31',
          initialDensity: '1.039-1.045',
          finalDensity: '1.006-1.014',
          name: 'Special Bitter',
          ABV: '3.7-4.8%',
          IBU: '25-40',
          SRM: '12-14',
          bgColor: 'bg-englishBitter',
          borderColor: 'border-englishBitterBorder',
        },
        {
          number: '45',
          initialDensity: '1.046-1.065',
          finalDensity: '1.010-1.018',
          name: 'Special Extra Bitter',
          ABV: '3.7-4.8%',
          IBU: '30-45',
          SRM: '12-14',
          bgColor: 'bg-englishBitter',
          borderColor: 'border-englishBitterBorder',
        },
      ]   
    },
    {
      title: 'SCOTISH ALE',
      titletextColor: 'text-scotishAleBorder',          
      elements: [
        {
          number: '19',
          initialDensity: '1.030-1.035',
          finalDensity: '1.006-1.012',
          name: 'Scottish Light 60/-',
          ABV: '2.8-4.0%',
          IBU: '9-20',
          SRM: '8-17',
          bgColor: 'bg-scotishAle',
          borderColor: 'border-scotishAleBorder',
        },
        {
          number: '32',
          initialDensity: '1.035-1.040',
          finalDensity: '1.010-1.014',
          name: 'Scottish Heavy 70/-',
          ABV: '3.5-4.1%',
          IBU: '12-25',
          SRM: '10-19',
          bgColor: 'bg-scotishAle',
          borderColor: 'border-scotishAleBorder',
        },
        {
          number: '46',
          initialDensity: '1.040-1.050',
          finalDensity: '1.010-1.018',
          name: 'Scottish Export 80/-',
          ABV: '4.0-4.9%',
          IBU: '15-36',
          SRM: '10-19',
          bgColor: 'bg-scotishAle',
          borderColor: 'border-scotishAleBorder',
        },
      ]   
    },
    {
      title: 'BROWN ALE',
      titletextColor: 'text-brownAleBorder',              
      elements: [
        {
          number: '20',
          initialDensity: '1.030-1.038',
          finalDensity: '1.004-1.012',
          name: 'English Mild',
          ABV: '2.5-4.1%',
          IBU: '10-24',
          SRM: '10-25',
          bgColor: 'bg-brownAle',
          borderColor: 'border-brownAleBorder',
        },
        {
          number: '33',
          initialDensity: '1.040-1.055',
          finalDensity: '1.010-1.018',
          name: 'American Brown',
          ABV: '4.2-6.0%',
          IBU: '25-60',
          SRM: '15-22',
          bgColor: 'bg-brownAle',
          borderColor: 'border-brownAleBorder',
        },
        {
          number: '47',
          initialDensity: '1.040-1.050',
          finalDensity: '1.008-1.014',
          name: 'English Brown',
          ABV: '3.5-6.0%',
          IBU: '15-25',
          SRM: '15-30',
          bgColor: 'bg-brownAle',
          borderColor: 'border-brownAleBorder',
        },
      ]   
    },
    {
      title: 'PORTER',
      titletextColor: 'text-porterBorder',             
      elements: [
        {
          number: '34',
          initialDensity: '1.040-1.050',
          finalDensity: '1.008-1.014',
          name: 'Brown Porter',
          ABV: '3.8-5.2%',
          IBU: '20-30',
          SRM: '20-30',
          bgColor: 'bg-porter',
          borderColor: 'border-porterBorder',
        },
        {
          number: '48',
          initialDensity: '1.050-1.065',
          finalDensity: '1.012-1.016',
          name: 'Robust Porter',
          ABV: '4.8-6.0%',
          IBU: '25-45',
          SRM: '30-40',
          bgColor: 'bg-porter',
          borderColor: 'border-porterBorder',
        },
      ]   
    },
    {
      title: 'STOUT',
      titletextColor: 'text-lightStoutBorder',                   
      elements: [
        {
          number: '21',
          initialDensity: '1.035-1.050',
          finalDensity: '1.008-1.014',
          name: 'Dry Stout',
          ABV: '3.2-5.5%',
          IBU: '40-50',
          SRM: '40+',
          bgColor: 'bg-lightStout',
          borderColor: 'border-lightStoutBorder',
        },
        {
          number: '35',
          initialDensity: '1.035-1.066',
          finalDensity: '1.010-1.022',
          name: 'Sweet Stout',
          ABV: '3.2-6.4%',
          IBU: '20-40',
          SRM: '40+',
          bgColor: 'bg-lightStout',
          borderColor: 'border-lightStoutBorder',
        },
        {
          number: '49',
          initialDensity: '1.035-1.060',
          finalDensity: '1.008-1.021',
          name: 'Oatmeal Stout',
          ABV: '3.3-6.1%',
          IBU: '20-50',
          SRM: '40+',
          bgColor: 'bg-lightStout',
          borderColor: 'border-lightStoutBorder',
        },
      ]   
    },
    {
      title: 'STOUT',
      titletextColor: 'text-heavyStoutBorder',                  
      elements: [
        {
          number: '22',
          initialDensity: '1.050-1.075',
          finalDensity: '1.010-1.017',
          name: 'Foreign Extra Stout',
          ABV: '5.0-7.5%',
          IBU: '35-70',
          SRM: '40+',
          bgColor: 'bg-heavyStout',
          borderColor: 'border-heavyStoutBorder',
        },
        {
          number: '36',
          initialDensity: '1.075-1.090',
          finalDensity: '1.020-1.030',
          name: 'Imperial Stout',
          ABV: '7.8-9.0%',
          IBU: '50-80',
          SRM: '40+',
          bgColor: 'bg-heavyStout',
          borderColor: 'border-heavyStoutBorder',
        },
        {
          number: '50',
          initialDensity: '1.075-1.100',
          finalDensity: '1.018-1.030',
          name: 'Pidorussian Imperial',
          ABV: '8.0-12.0%',
          IBU: '50-90',
          SRM: '40+',
          bgColor: 'bg-heavyStout',
          borderColor: 'border-heavyStoutBorder',
        },
      ]   
    },
    {
      title: 'PILSNER',
      titletextColor: 'text-pilsnerBorder',               
      elements: [
        {
          number: '23',
          initialDensity: '1.044-1.050',
          finalDensity: '1.006-1.012',
          name: 'German Pilsner',
          ABV: '4.6-5.4%',
          IBU: '25-45',
          SRM: '2-4',
          bgColor: 'bg-pilsner',
          borderColor: 'border-pilsnerBorder',
        },
        {
          number: '37',
          initialDensity: '1.044-1.056',
          finalDensity: '1.014-1.020',
          name: 'Bohemian Pilsner',
          ABV: '4.1-5.1%',
          IBU: '35-45',
          SRM: '3-5',
          bgColor: 'bg-pilsner',
          borderColor: 'border-pilsnerBorder',
        },
        {
          number: '51',
          initialDensity: '1.055-1.060',
          finalDensity: '1.012-1.018',
          name: 'American Pilsner',
          ABV: '5.0-6.0%',
          IBU: '20-40',
          SRM: '3-6',
          bgColor: 'bg-pilsner',
          borderColor: 'border-pilsnerBorder',
        },
      ]   
    },
    {
      title: 'AMERICAN LAGER',
      titletextColor: 'text-americanLagerBorder', 
      elements: [
        {
          number: '11',
          initialDensity: '1.024-1.040',
          finalDensity: '1.002-1.008',
          name: 'American Lite',
          ABV: '2.9-4.5%',
          IBU: '8-15',
          SRM: '2-4',
          bgColor: 'bg-americanLager',
          borderColor: 'border-americanLagerBorder',
        },
        {
          number: '24',
          initialDensity: '1.040-1.046',
          finalDensity: '1.006-1.010',
          name: 'American Standard',
          ABV: '4.1-4.8%',
          IBU: '5-17',
          SRM: '2-6',
          bgColor: 'bg-americanLager',
          borderColor: 'border-americanLagerBorder',
        },
        {
          number: '38',
          initialDensity: '1.046-1.050',
          finalDensity: '1.010-1.014',
          name: 'American Premium',
          ABV: '4.6-5.1%',
          IBU: '13-23',
          SRM: '2-8',
          bgColor: 'bg-americanLager',
          borderColor: 'border-americanLagerBorder',
        },
        {
          number: '52',
          initialDensity: '1.040-1.050',
          finalDensity: '1.008-1.012',
          name: 'American Dark',
          ABV: '4.1-5.6%',
          IBU: '14-20',
          SRM: '10-20',
          bgColor: 'bg-americanLager',
          borderColor: 'border-americanLagerBorder',
        },
      ]   
    },
    {
      title: 'EUROPEAN LAGER',
      titletextColor: 'text-europeanLagerBorder',
      elements: [
        {
          number: '12',
          initialDensity: '1.044-1.050',
          finalDensity: '1.008-1.012',
          name: 'Munich Helles',
          ABV: '4.5-5.6%',
          IBU: '18-25',
          SRM: '3-5',
          bgColor: 'bg-europeanLager',
          borderColor: 'border-europeanLagerBorder',
        },
        {
          number: '25',
          initialDensity: '1.048-1.056',
          finalDensity: '1.010-1.014',
          name: 'Dort- munder',
          ABV: '5.1-6.1%',
          IBU: '23-29',
          SRM: '4-6',
          bgColor: 'bg-europeanLager',
          borderColor: 'border-europeanLagerBorder',
        },
        {
          number: '39',
          initialDensity: '1.052-1.056',
          finalDensity: '1.010-1.014',
          name: 'Munich Dunkel',
          ABV: '4.8-5.4%',
          IBU: '16-25',
          SRM: '17-23',
          bgColor: 'bg-europeanLager',
          borderColor: 'border-europeanLagerBorder',
        },
        {
          number: '53',
          initialDensity: '1.044-1.052',
          finalDensity: '1.012-1.016',
          name: 'Schwarz- bier',
          ABV: '3.8-5.0%',
          IBU: '22-30',
          SRM: '25-40+',
          bgColor: 'bg-europeanLager',
          borderColor: 'border-europeanLagerBorder',
        },
      ]   
    },
    {
      title: 'BOCK',
      titletextColor: 'text-bockLagerBorder',
      elements: [
        {
          number: '13',
          initialDensity: '1.066-1.074',
          finalDensity: '1.011-1.020',
          name: 'Helles Bock',
          ABV: '6.0-7.5%',
          IBU: '20-35',
          SRM: '4-10',
          bgColor: 'bg-bockLager',
          borderColor: 'border-bockLagerBorder',
        },
        {
          number: '26',
          initialDensity: '1.074-1.080',
          finalDensity: '1.020-1.028',
          name: 'Doppel- bock',
          ABV: '6.6-7.9%',
          IBU: '20-30',
          SRM: '12-30',
          bgColor: 'bg-bockLager',
          borderColor: 'border-bockLagerBorder',
        },
        {
          number: '40',
          initialDensity: '1.066-1.074',
          finalDensity: '1.018-1.024',
          name: 'Traditional Bock',
          ABV: '6.4-7.6%',
          IBU: '20-30',
          SRM: '15-30',
          bgColor: 'bg-bockLager',
          borderColor: 'border-bockLagerBorder',
        },
        {
          number: '54',
          initialDensity: '1.090-1.116',
          finalDensity: '1.023-1.035',
          name: 'Eisbock',
          ABV: '8.7-14.4%',
          IBU: '25-50',
          SRM: '18-40+',
          bgColor: 'bg-bockLager',
          borderColor: 'border-bockLagerBorder',
        },
      ]   
    },
  ];


  return (
    <div className="container flex justify-center items-end flex-wrap gap-3 mx-auto myxl:w-full xl:w-[55%] md:w-[65%] sm:w-[80%]">
      {beerElements.map(el => {
        return  <div className="flex flex-col gap-3">
        <BeerColumnTitle 
          title={el.title}
          titletextColor={el.titletextColor}          
        />
        
        {el.elements.map(subElement => {
          return <BeerElement
          number={subElement.number}
          initialDensity={subElement.initialDensity}
          finalDensity={subElement.finalDensity}
          name={subElement.name}
          ABV={subElement.ABV}
          IBU={subElement.IBU}
          SRM={subElement.SRM}
          bgColor={subElement.bgColor}
          borderColor={subElement.borderColor}
        />
        })}

      </div> 
      })}

      

    </div>
  );
}